version: '3.4'

services:
    
  mysqldb:
   image: mysql
   command: mysqld --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: rootp
     MYSQL_DATABASE: PromoIt
     MYSQL_USER: admin
     MYSQL_PASSWORD: admin
   ports:
       - "3307:3306"
       - "8889:8889"
       - "33061:33061"
       - "33062:33062"
   working_dir: /var/lib/mysql1
   volumes:
       - "./mysql:/var/lib/mysql1:rw"

  adminer:
   image: adminer
   restart: always
   ports:
     - 8900:8080
      
volumes: 
  vol_cosmos:
  mysql: